// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  // Canonical https URL (used for canonical tags + sitemap). Served via the
  // Cloudflare custom domain configured in wrangler.jsonc.
  site: 'https://engram.seanb4t.dev',
  integrations: [
    starlight({
      title: 'engram',
      description:
        'Self-hosted, correctable, OAuth-secured memory for coding agents, over MCP.',
      customCss: ['./src/styles/brand.css'],
      logo: { src: './src/assets/engram-mark.svg', replacesTitle: true },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/seanb4t/engram',
        },
      ],
      sidebar: [
        // A labeled group whose entries are autogenerated from a directory is
        // `{ label, items: [{ autogenerate: { directory } }] }` — `autogenerate`
        // is a sidebar ITEM nested in `items`, NOT a sibling of `label`. (The
        // bare `{ label, autogenerate }` form is not valid in current Starlight.)
        { label: 'Guides', items: [{ autogenerate: { directory: 'guides' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
        { label: 'Contributing', items: [{ autogenerate: { directory: 'contributing' } }] },
      ],
    }),
  ],
});
