// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  // v1 ships on the *.workers.dev subdomain. When a custom domain is chosen,
  // set this to the canonical https URL (used for canonical tags + sitemap).
  site: 'https://engram-docs.workers.dev',
  integrations: [
    starlight({
      title: 'engram',
      description:
        'Self-hosted, correctable, OAuth-secured memory for coding agents, over MCP.',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/seanb4t/engram',
        },
      ],
      sidebar: [
        // A labeled group whose entries are autogenerated from a directory is
        // `{ label, items: [{ autogenerate: { directory } }] }` — `autogenerate`
        // is a sidebar ITEM nested in `items`, NOT a sibling of `label`. (The
        // bare `{ label, autogenerate }` form is not valid in current Starlight.)
        { label: 'Guides', items: [{ autogenerate: { directory: 'guides' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
        { label: 'Contributing', items: [{ autogenerate: { directory: 'contributing' } }] },
      ],
    }),
  ],
});
