// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sean Brandt

package server

import (
	"errors"
	"strings"
	"time"

	"github.com/seanb4t/engram/internal/store"
)

// errStaleSummary rejects an update that would silently strand a caller-authored
// summary against changed content. Actionable: the agent must choose.
var errStaleSummary = errors.New(
	`content changed but a caller-authored summary would go stale: ` +
		`re-send the same summary to keep it, pass an updated one, or pass summary="" to clear it`)

// resolveSummaryUpdate decides what to persist for a record's summary during an
// update. arg==nil means the caller did not address the summary. apply==true
// means set the summary to value (value=="" clears).
func resolveSummaryUpdate(cur store.Memory, contentChanged bool, arg *string) (value string, apply bool, err error) {
	if arg != nil {
		return *arg, true, nil // explicit set or clear
	}
	if !contentChanged || cur.Summary == "" {
		return "", false, nil // preserve / nothing to lose
	}
	if cur.SummarySource == store.SummarySourceAuto {
		return "", true, nil // server-derived: auto-clear, regenerated by next sweep
	}
	if cur.SummarySource == store.SummarySourceClient {
		return "", false, errStaleSummary // caller-authored: refuse to silently strand
	}
	return "", false, nil // unknown/legacy provenance: preserve silently
}

// recallView is the compact, summary-shaped recall result.
type recallView struct {
	ID            string    `json:"id"`
	ShortID       string    `json:"short_id,omitempty"`
	Summary       string    `json:"summary"`
	SummarySource string    `json:"summary_source,omitempty"`
	Truncated     bool      `json:"truncated,omitempty"`
	Scope         string    `json:"scope"`
	Category      string    `json:"category"`
	Tags          []string  `json:"tags,omitempty"`
	CreatedAt     time.Time `json:"created_at"`
	// Score is the Qdrant similarity score on search results (higher = closer);
	// omitted (zero) on list results, which are not ranked.
	Score float32 `json:"score,omitempty"`
	// AccessCount / LastAccessedAt are the D-07 read-only usage-signal curation
	// fields (Phase 12). recallView is a hand-written allow-list — these must
	// be explicitly added here AND populated in toRecallView to surface on the
	// compact list/search shape; store.Memory carrying the fields alone is not
	// enough.
	AccessCount    uint64     `json:"access_count"`
	LastAccessedAt *time.Time `json:"last_accessed_at,omitempty"`
}

// summaryOrTruncation is the value the recall path shows in place of content:
// the stored summary, else a truncation. The bool reports truncation.
func summaryOrTruncation(m store.Memory, maxChars int) (string, bool) {
	if m.Summary != "" {
		return m.Summary, false
	}
	return truncateForRecall(m.Content, maxChars)
}

// truncateForRecall returns a head-truncation of content (rune-safe) and whether
// it was cut. Short content is returned unchanged.
func truncateForRecall(content string, maxChars int) (string, bool) {
	r := []rune(content)
	if len(r) <= maxChars {
		return content, false
	}
	return strings.TrimRight(string(r[:maxChars]), " ") + "…", true
}

// shapeRecall renders memories for a recall response: full store.Memory values
// when full, else compact summary-shaped recallView values.
func shapeRecall(ms []store.Memory, full bool, maxChars int) []any {
	out := make([]any, len(ms))
	for i, m := range ms {
		if full {
			out[i] = m
		} else {
			out[i] = toRecallView(m, maxChars)
		}
	}
	return out
}

// toRecallView shapes one memory for default (summary) recall.
func toRecallView(m store.Memory, maxChars int) recallView {
	summary, truncated := summaryOrTruncation(m, maxChars)
	return recallView{
		ID: m.ID, ShortID: m.ShortID, Summary: summary, SummarySource: string(m.SummarySource), Truncated: truncated,
		Scope: m.Scope, Category: m.Category, Tags: m.Tags, CreatedAt: m.CreatedAt,
		Score:          m.Score,
		AccessCount:    m.AccessCount,
		LastAccessedAt: m.LastAccessedAt,
	}
}
